[package]
name = "engine"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
log = "0.4.17"
rayon = "1.6.0"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 3